---
argument_specs:
  main:
    short_description: Main entry point for faults role
    description:
      - This is the main entry point for the environment role.
      - This role is responsible for modifying the environment before fault injection and after fault removal.
    author:
      - Gerard Vanloo
    options:
      faults_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            default: ~/.kube/config
            required: false
            type: str
      faults_specs:
        elements: dict
        required: true
        type: list
        options:
          chaos_mesh:
            required: false
            type: dict
            options:
              schedule:
                required: true
                type: dict
                options:
                  name:
                    required: true
                    type: str
                  spec:
                    required: true
                    type: dict
          custom:
            required: false
            type: dict
            options:
              name:
                choices:
                  - invalid-command
                  - invalid-image
                  - invalid-node-selector
                  - misconfigured-horizontal-pod-autoscaler
                  - misconfigured-network-policy
                  - misconfigured-persitent-volume-claim
                  - misconfigured-resource-quota
                  - misconfigured-service-port
                  - modify-environment-variables
                  - unsupported-image
                required: true
                type: str
              invalid_command:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      container:
                        required: true
                        type: dict
                        options:
                          name:
                            required: false
                            type: str
                      kind:
                        choices:
                          - Deployment
                          - ReplicaSet
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
                  restart_policy:
                    choices:
                      - force
                      - safe
                    default: force
                    required: false
                    type: str
              invalid_image:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      container:
                        required: true
                        type: dict
                        options:
                          name:
                            required: false
                            type: str
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
                  restart_policy:
                    choices:
                      - force
                      - safe
                    default: force
                    required: false
                    type: str
              invalid_node_selector:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
              misconfigured_horizontal_pod_autoscaler:
                required: false
                type: dict
                options:
                  autoscaler:
                    required: true
                    type: dict
                    options:
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
              misconfigured_network_policy:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
              misconfigured_persitent_volume_claim:
                required: false
                type: dict
                options:
                  workload:
                    elements: dict
                    required: true
                    type: list
                    options:
                      container:
                        required: true
                        type: dict
                        options:
                          name:
                            required: false
                            type: str
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
              misconfigured_resource_quota:
                required: false
                type: dict
                options:
                  namespace:
                    required: false
                    type: dict
                    options:
                      name:
                        required: true
                        type: str
                  workloads:
                    elements: dict
                    required: true
                    type: list
                    options:
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
              misconfigured_service_port:
                required: false
                type: dict
                options:
                  service:
                    required: false
                    type: dict
                    options:
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
                      target_port:
                        required: true
                        type: int
              modify_environment_variables:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
                      container:
                        required: true
                        type: dict
                        options:
                          name:
                            required: false
                            type: str
                          env:
                            elements: dict
                            required: true
                            type: list
                            options:
                              name:
                                required: true
                                type: str
                              value:
                                required: true
                                type: str
                  restart_policy:
                    choices:
                      - force
                      - safe
                    default: force
                    required: false
                    type: str
              unsupported_image:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      container:
                        required: true
                        type: dict
                        options:
                          name:
                            required: false
                            type: str
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
                  restart_policy:
                    choices:
                      - force
                      - safe
                    default: force
                    required: false
                    type: str
          otel_demo:
            required: false
            type: dict
            options:
              flagd:
                required: false
                type: dict
                options:
                  flags:
                    elements: dict
                    required: true
                    type: list
                    options:
                      name:
                        choices:
                          - adHighCpu
                          - adFailure
                          - adManualGc
                          - cartFailure
                          - imageSlowLoad
                          - kafkaQueueProblems
                          - loadGeneratorFloodHomepage
                          - paymentFailure
                          - paymentUnreachable
                          - productCatalogFailure
                          - recommendationCacheFailure
                        required: true
                        type: str
                      state:
                        required: true
                        type: str
          valkey:
            required: false
            type: dict
            options:
              name:
                choices:
                  - invalid-password
                required: true
                type: str
              invalid_password:
                required: false
                type: dict
                options:
                  workload:
                    required: true
                    type: dict
                    options:
                      kind:
                        choices:
                          - Deployment
                          - StatefulSet
                        required: true
                        type: str
                      name:
                        required: true
                        type: str
                      namespace:
                        required: true
                        type: str
