---
metadata:
  complexity: Medium
  id: 3
  name: Ad Service CPU
  platform: kubernetes
spec:
  environment:
    applications:
      otel_demo:
        enabled: true
    tools:
      category: sre
      selected:
        - kubernetes-topology-monitor
  faults:
    - otel_demo:
        flagd:
          flags:
            - name: adHighCpu
              state: "on"
