---
- name: Get AWX secret information
  kubernetes.core.k8s_info:
    kind: Secret
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    name: awx-deployment-admin-password
    namespace: "{{ awx_helm_releases.awx_operator.namespace }}"
    wait: true
  register: awx_secret_info

- name: Extract the AWX password
  ansible.builtin.set_fact:
    awx_controller_password: "{{ awx_secret_info.resources[0].data.password | b64decode }}" # pragma: allowlist secret
