---
- name: Uninstall AWX
  kubernetes.core.k8s:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx-deployment
        namespace: "{{ awx_helm_releases.awx_operator.namespace }}"
    state: absent
    wait: true

- name: Uninstall AWX operator
  kubernetes.core.helm:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    release_name: "{{ awx_helm_releases.awx_operator.name }}"
    release_namespace: "{{ awx_helm_releases.awx_operator.namespace }}"
    release_state: absent
    timeout: 10m0s
    wait: true

- name: Delete experiment data PersistentVolumeClaim
  kubernetes.core.k8s:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: experiment-data-pvc
        namespace: "{{ awx_helm_releases.awx_operator.namespace }}"
    state: absent
    wait: true
    wait_timeout: 300
  when:
    - awx_cluster.provider == "kind"

- name: Delete experiment data PersistentVolume
  kubernetes.core.k8s:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: experiment-data-pv
    state: absent
    wait: true
    wait_timeout: 300
  when:
    - awx_cluster.provider == "kind"

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ awx_helm_releases.awx_operator.namespace }}"
    state: absent
    wait: true
