---
argument_specs:
  main:
    short_description: Main entry point for tools role
    description:
      - This is the main entry point for the tools role.
      - This role is responsible for installing and uninstalling tools and services.
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          provider:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      tools_required:
        required: true
        type: dict
        options:
          chaos_mesh:
            required: true
            type: bool
          clickhouse:
            required: true
            type: bool
          ingress:
            required: true
            type: bool
          istio:
            required: true
            type: bool
          jaeger:
            required: true
            type: bool
          kubernetes_metrics_server:
            required: true
            type: bool
          kubernetes_topology_monitor:
            required: true
            type: bool
          opencost:
            required: true
            type: bool
          opensearch:
            required: true
            type: bool
          opentelemetry:
            required: true
            type: bool
          prometheus:
            required: true
            type: bool
  set_clickhouse_credentials:
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
  set_clickhouse_endpoint:
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
  set_ingress_hostname:
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
  set_prometheus_endpoint:
    short_description: Main entry point for tools role
    description:
      - This is the main entry point for the tools role.
      - This role is responsible for installing and uninstalling tools and services.
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: false
        type: dict
        options:
          kubeconfig:
            default: ~/.kube/config
            required: false
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            default: kubernetes
            required: false
            type: str
