---
applications_configurations:
  otel_demo:
    accounting:
      autoscaling: false
      replicas: 1
    ad:
      autoscaling: false
      replicas: 1
    cart:
      autoscaling: false
      replicas: 1
    checkout:
      autoscaling: false
      replicas: 1
    currency:
      autoscaling: false
      replicas: 1
    email:
      autoscaling: false
      replicas: 1
    fraud_detection:
      autoscaling: false
      replicas: 1
    frontend:
      autoscaling: false
      replicas: 1
    frontend_proxy:
      autoscaling: false
      replicas: 1
    image_provider:
      autoscaling: false
      replicas: 1
    kafka:
      autoscaling: false
      replicas: 1
    load_generator:
      spawn_rate: 5
      users: 50
    otel_collector: {}
    payment:
      autoscaling: false
      replicas: 1
    postgres:
      autoscaling: false
      replicas: 1
    product_catalog:
      autoscaling: false
      replicas: 1
    quote:
      autoscaling: false
      replicas: 1
    recommendation:
      autoscaling: false
      replicas: 1
    shipping:
      autoscaling: false
      replicas: 1
    valkey_cart:
      autoscaling: false
      replicas: 1
