---
# This definition has been left purposely incomplete. This allows
# Dependabot to track the image. The full definition is provided in the
# template version of this object.

apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger
spec:
  image: docker.io/jaegertracing/jaeger:2.11.0
