---
# This definition has been left purposely incomplete. This allows
# Dependabot to track the image. The full definition is provided in the
# template version of this object.

apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: kubernetes
spec:
  image: quay.io/it-bench/opentelemetry-collector:1.0.0
