---
# This definition has been left purposely incomplete. This allows
# Dependabot to track the image. The full definition is provided in the
# template version of this object.

apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-topology-recorder
spec:
  template:
    spec:
      containers:
        - name: recorder
          image: registry.access.redhat.com/ubi10/python-312-minimal:10.0-1758744656
