---
- name: Create the release namespace for Clickhouse Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.namespace }}"
        labels:
          it-bench/monitoring: "true"
    state: present

- name: Install Clickhouse Operator
  kubernetes.core.helm:
    chart_ref: altinity-clickhouse-operator
    chart_repo_url: https://docs.altinity.com/clickhouse-operator/
    chart_version: 0.25.4
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      configs:
        files:
          config.yaml:
            watch:
              namespaces:
                - "{{ instance.namespace }}"
      podAnnotations:
        openshift.io/required-scc: restricted-v2
      serviceMonitor:
        enabled: "{{ tools_required.prometheus }}"
    wait: true

- name: Create the release namespace for Clickhouse
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ instance.namespace }}"
        annotations:
          openshift.io/sa.scc.mcs: s0:c30,c10
          openshift.io/sa.scc.uid-range: 100/100
          openshift.io/sa.scc.supplemental-groups: 101/100
        labels:
          it-bench/monitoring: "true"
    state: present

- name: Create Clickhouse Kubernetes objects
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ instance.namespace }}"
    state: present
    src: files/clickhouse/{{ item }}
  loop:
    - secret.yaml
    - templates.yaml
    - installation.yaml

- name: Wait for Clickhouse install to complete
  kubernetes.core.k8s_info:
    api_version: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: "{{ instance.name }}"
    namespace: "{{ instance.namespace }}"
    wait: true
  register: tools_clickhouse_installation_info
  until:
    - tools_clickhouse_installation_info.resources | length > 0
    - tools_clickhouse_installation_info.resources[0].status is defined
    - tools_clickhouse_installation_info.resources[0].status.status is defined
    - tools_clickhouse_installation_info.resources[0].status.status == 'Completed'
  retries: 10
  delay: 30
