---
- name: Uninstall Prometheus Operator and Prometheus
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: absent
    wait: true
  when:
    - tools_cluster.platform == "kubernetes"

- name: Retrieve all CRDs
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
  register: tools_crd_info
  when:
    - tools_cluster.platform == "kubernetes"

- name: Remove the Prometheus Operator related CRDs from the cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: "{{ item }}"
    state: absent
    wait: true
  loop: |
    {{
      tools_crd_info.resources |
      selectattr('spec.group', '==', 'monitoring.coreos.com') |
      community.general.json_query('[*].metadata.name')
    }}
  when:
    - tools_cluster.platform == "kubernetes"

- name: Disable OpenShift user workload monitoring
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    state: absent
    src: files/openshift/user-workload-monitoring-config.yaml
  when:
    - tools_cluster.platform == "openshift"

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.namespace }}"
    state: absent
    wait: true
